### ISSUE TITLE
Compatibility problem caused by a past commit

### ISSUE THREAD

**Issue by dominik-polic** [ROBOTIS-GIT/turtlebot3_home_service_challenge#25]
I've been trying to get the home service challenge working with the real life Turtlebot 3 robot and I've encountered a couple of issues, but this specific one is caused by [this commit](https://github.com/ROBOTIS-GIT/turtlebot3_home_service_challenge/commit/e2f16706e2d08597db573f305b22d7974549c365) as part of [this contribution](https://github.com/ROBOTIS-GIT/turtlebot3_home_service_challenge/pull/13). As far as I can tell, this is present on all branches other than `kinetic-devel`. 

The issue is removal of "/" symbols in `global_frame: /map`, `robot_base_frame: /tb3_hsc/base_footprint` and simmilar lines in all the files in the mentioned contribution. This causes an error when running the navigation example as all the frames are interpreted with an extra `tb3_hsc` at the begining (`/map` becomes `/tb3_hsc/map` and `/tb3_hsc/base_footprint` becomes `/tbr_hsc/tb3_hsc/base_footprint`).
This basically breaks everything as those frames are named wrong and don't exist. Reverting the entire commit fixes the issue completely. 

I am, however, running this on ROS Kinetic, so it is possible that it's not the problem on other distributions, in which case feel free to close this issue, although I believe it would be beneficial to check that's the case first.

**Comment by ROBOTIS-Will** [comment]
Hi @dominik-polic 
The change in tf prefix has applied since Melodic and does not affect to `kinetic-devel` as Kinetic is discontinued and not had been updated.
If you are running Kinetic version, you should use a specific `kinetic-devel` branch instead of the `master`.
I've revised the eManual instruction so that the correct branch can be used for Kinetic users.
https://github.com/ROBOTIS-GIT/emanual/commit/f6ca849de73f2931a79b0e854d8c880e0e991351

Thank you.

**Comment by dominik-polic** [comment]
Hi @ROBOTIS-Will 
Thank you for the clarification. In that case, I will mark this issue as closed.
